pre-commit:
  jobs:
    - name: Format JS-Like, Json(c) & Yaml
      run: ./node_modules/prettier/bin/prettier.cjs --write {staged_files}
      glob:
        - "*.{js,jsx,cjs,mjx,ts,tsx,cts,mts,yml,yaml,json,jsonc}"
      stage_fixed: true
